# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="sorin"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias digg="dig +nocmd any +multiline +noall +answer"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(autojump bundler git osx gem brew rbenv)

source ~/.git-prompt.sh
source $ZSH/oh-my-zsh.sh

eval "$(rbenv init -)"
# Customize to your needs...
export PATH=./bin:~/.rbenv/bin:~/.rbenv/shims:~/bin:/usr/local/sbin:~/.rbenv/bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/CrossPack-AVR/bin

setopt extendedglob

# down with autocorrect
unsetopt correct_all

# from the old bashrc
export GIT_EDITOR="mate --name 'Git Commit Message' -w -l 1"
export EDITOR='mvim -f'
export ALTERNATE_EDITOR="mate -w"

# That makefile for arduino stuff
export ARDUINO_DIR=/Applications/Arduino.app/Contents/Resources/Java
export ARDMK_DIR=/usr/local/CrossPack-AVR


  [[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
