# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="sorin"
HISTDUP=erase
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

function git_prompt_info() {}
function git_prompt_status() {}
function compdef() {}
source ~/.git-prompt.sh

setopt promptsubst

alias digg="dig +nocmd any +multiline +noall +answer"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(autojump)
plugins_defered=(git osx gem ruby rbenv bundler)

source ~/.async.zsh
autoload -Uz async && async
async_init

# Initialize a new worker (with notify option)
async_start_worker my_worker -n

VAR=0

# Create a callback function to process results
function completed_callback() {
    if [ $VAR -eq 0 ]; then
      source $ZSH/oh-my-zsh.sh
      VAR=$((VAR+1))
      async_job my_worker sleep 0.1
    elif [ $VAR -ge 1 ]; then
      plugin=$plugins_defered[$VAR]
      if [ ! -z "$plugin" ]; then
        source $ZSH/plugins/$plugin/$plugin.plugin.zsh
        VAR=$((VAR+1))
        async_job my_worker sleep 0.1
      else
        alias ls="ls -G --color"

        export PATH="./bin:~/bin:$PATH"
      fi
    fi
}

source $ZSH/lib/history.zsh
source $ZSH/lib/theme-and-appearance.zsh
source $ZSH/themes/$ZSH_THEME.zsh-theme

# Register callback function for the workers completed jobs
async_register_callback my_worker completed_callback

# Give the worker some tasks to perform
# async_job my_worker
async_job my_worker sleep 0.1

# Customize to your needs...
export PATH=~/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Postgres bins
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"

setopt extendedglob

# down with autocorrect
unsetopt correct_all

# The Editors!
export GIT_EDITOR="emacsclient"
export EDITOR='emacsclient'
export ALTERNATE_EDITOR="emacs"

#lazy load autojump
function j() {
    (( $+commands[brew] )) && {
        local pfx=$(brew --prefix)
        [[ -f "$pfx/etc/autojump.sh" ]] && . "$pfx/etc/autojump.sh"
        j "$@"
    }
}


[[ $TERM_PROGRAM == "iTerm.app" ]] && test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export RAILS_VERSION=5.0

# Node >=7 dependency
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH="/usr/local/opt/node@8/bin:$PATH"
# coreutils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# gnu-sed
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

# eval "$(rbenv init -)"
